//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.FEW.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EIS.FEW.Resources.Localizing", typeof(Localizing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật không thành công. Mã CSKCB và Năm đã tồn tại!.
        /// </summary>
        internal static string MessageAddId {
            get {
                return ResourceManager.GetString("MessageAddId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng thời gian này có chứa 1 khoảng thời gian khác trong danh mục.
        /// </summary>
        internal static string MessageBaoKhoangThoiGian {
            get {
                return ResourceManager.GetString("MessageBaoKhoangThoiGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng kiểm tra lại dữ liệu!.
        /// </summary>
        internal static string MessageCommon {
            get {
                return ResourceManager.GetString("MessageCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng nhập ngày bắt đầu nhỏ hơn ngày kết thúc!.
        /// </summary>
        internal static string MessageDate {
            get {
                return ResourceManager.GetString("MessageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng nhập ngày kết thúc!.
        /// </summary>
        internal static string MessageDateEnd {
            get {
                return ResourceManager.GetString("MessageDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng nhập ngày bắt đầu!.
        /// </summary>
        internal static string MessageDateStart {
            get {
                return ResourceManager.GetString("MessageDateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng nhập ngày bắt đầu và ngày kết thúc!.
        /// </summary>
        internal static string MessageDatetime {
            get {
                return ResourceManager.GetString("MessageDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã xóa bản ghi thành công!.
        /// </summary>
        internal static string MessageDelete {
            get {
                return ResourceManager.GetString("MessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá bản ghi không thành công, vui lòng kiểm tra lại!.
        /// </summary>
        internal static string MessageDeleteError {
            get {
                return ResourceManager.GetString("MessageDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đã tồn tại, vui lòng nhập lại mã khác!.
        /// </summary>
        internal static string MessageID {
            get {
                return ResourceManager.GetString("MessageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu không thành công, vui lòng kiểm tra lại!.
        /// </summary>
        internal static string MessageInsert {
            get {
                return ResourceManager.GetString("MessageInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày và đến ngày không được nằm trong khoảng thời gian đã có trước đó.
        /// </summary>
        internal static string MessageKhoangTuNgayDenNgay {
            get {
                return ResourceManager.GetString("MessageKhoangTuNgayDenNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã thực hiện thành công!.
        /// </summary>
        internal static string MessageSuccess {
            get {
                return ResourceManager.GetString("MessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày không được lớn hơn đến ngày.
        /// </summary>
        internal static string MessageTuNgayDenNgay {
            get {
                return ResourceManager.GetString("MessageTuNgayDenNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật không thành công, vui lòng kiểm tra lại!.
        /// </summary>
        internal static string MessageUpdate {
            get {
                return ResourceManager.GetString("MessageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật không thành công. Mã CSKCB không đúng!.
        /// </summary>
        internal static string MessageUpdateNotId {
            get {
                return ResourceManager.GetString("MessageUpdateNotId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật không thành công. Không tìm thấy năm trong hệ thống!.
        /// </summary>
        internal static string MessageUpdateNotNam {
            get {
                return ResourceManager.GetString("MessageUpdateNotNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật không thành công. cơ sở KCB và  Năm đã tồn tại!.
        /// </summary>
        internal static string MessageUpdateNotNamCSKCB {
            get {
                return ResourceManager.GetString("MessageUpdateNotNamCSKCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm/sửa thông tin.
        /// </summary>
        internal static string PopupEditFormCaption {
            get {
                return ResourceManager.GetString("PopupEditFormCaption", resourceCulture);
            }
        }
    }
}
